### PR TITLE
Updated all url's to cloudflare

### PR DESCRIPTION
**Pull request by brendonbeebe**
Most the links in the documentation are broken and pointing to the old
repository.

### CODE REVIEW

**Comment by emileber** [comment]
@wyuenho This should get merged. It would fix issue #664

**Comment by brendonbeebe** [comment]
@wyuenho Where is http://backgridjs.com/ hosted?  The links on there are all out of date.

**Comment by wyuenho** [comment]
The API should be on cloudflare.github.io. The docs should be on the backgridjs.com repo. I thought I updated it, but maybe I didn't. Would appreciate it if you could only a PR there.

**Comment by wyuenho** [comment]
Should be fixed now

**Comment by brendonbeebe** [comment]
Awesome, thanks @wyuenho

**Pull request merged**
